version: 2.1 
jobs: 
  node-1.0.16.3: &template
    docker: 
      - image: circleci/node:10.16.3
    steps: 
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-project
          command: npm ci
      - run:
          name: test
          command: npm test
      - run:
          name: start
          command: npm start
      - run:
          name: stop
          command: npm stop
      - run:
          name: delete
          command: npm run delete
  node-lts:
    <<: *template
    docker:
        - image: circleci/node:lts
  node-latest:
    <<: *template
    docker:
        - image: circleci/node:latest


workflows:
  version: 2
  build_and_test:
    jobs:
      - node-1.0.16.3
      - node-lts
      - node-latest


      