version: 2
# Trabajos en paralelo para cada version de Node
workflows:
  version: 2
  build-and-test:
    jobs:
      - node-10.16.3
      - node-lts
      - node-latest

jobs:
  # Crear template y repetir en otras versiones de node
  node-10.16.3: &build-template
    docker: 
      - image: circleci/node:10.16.3
    steps: 
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-project
          command: npm ci
      - run:
          name: test
          command: npm test
      - run:
          name: start
          command: npm start
      - run:
          name: stop
          command: npm stop
      - run:
          name: delete
          command: npm run delete
  node-lts:
    <<: *build-template
    docker:
        - image: circleci/node:lts
  node-latest:
    <<: *build-template
    docker:
        - image: circleci/node:latest



      